from typing import Protocol

class OTPStorage(Protocol):
    async def store_otp(self, mobile: str, otp: str) -> None: ...
    async def get_otp(self, mobile: str, otp: str) -> bool: ...
    async def delete_otp(self, mobile: str) -> None: ...
    async def increment_attempts(self, mobile: str) -> int: ...
    async def clear_attempts(self, mobile: str) -> None: ...
    async def verify_with_limits(self, mobile: str, otp: str) -> bool: ...
    
class MessagePublisher(Protocol):
    async def publish_sms_job(self, mobile: str, otp: str) -> None: ...